-- --CREATING DATABASE
-- CREATE DATABASE UNIVERSITY; 

-- USE UNIVERSITY;

-- CREATING TABLES

-- DROP TABLE HEADED_BY, BELONGS_TO, OPTS_FOR, OFFERS, DEPARTMENT, TEACHER, STUDENT, COURSE;

-- CREATE TABLE DEPARTMENT (
--     D_NO int PRIMARY KEY, 
--     D_NAME varchar(20) UNIQUE NOT NULL, 
--     LOC varchar(20) DEFAULT ' - '
-- );

-- CREATE TABLE TEACHER (
--     NAME varchar(20) UNIQUE NOT NULL,
--     PHONENO varchar(10) UNIQUE DEFAULT 'xxxxxxxx',
--     EMAILID varchar(40) UNIQUE NOT NULL,
--     T_ID varchar(15) PRIMARY KEY
-- );

-- CREATE TABLE STUDENT (
--     NAME varchar(20) UNIQUE NOT NULL,
--     PHONENO varchar(10) UNIQUE DEFAULT 'xxxxxxxx',
--     EMAILID varchar(40) UNIQUE NOT NULL,
--     S_ID varchar(15) PRIMARY KEY,
--     ROLLNO int,
--     BATCH varchar(25) NOT NULL,
--     CONSTRAINT CHK_RollNo CHECK (ROLLNO>0 AND ROLLNO<200)
-- );

-- CREATE TABLE COURSE (
--     C_ID varchar(15) PRIMARY KEY,
--     C_NAME varchar(20) UNIQUE NOT NULL,
--     CREDITS int DEFAULT 2,
--     LENGTH int DEFAULT 10,  --DURATION IN HRS
--     CONSTRAINT CHK_Credits CHECK (CREDITS>0 AND CREDITS<6),
--     CONSTRAINT CHK_Length CHECK (LENGTH>0 AND LENGTH<60)
-- );

-- CREATE TABLE HEADED_BY (
--     DeptNo int NOT NULL REFERENCES DEPARTMENT(D_NO), 
--     HeadOfDept varchar(15) NOT NULL REFERENCES TEACHER(T_ID), 
--     CONSTRAINT PK_HEADED_BY PRIMARY KEY (DeptNo, HeadOfDept)
-- );

-- CREATE TABLE BELONGS_TO (
--     DeptNo int NOT NULL REFERENCES DEPARTMENT(D_NO), 
--     TeacherID varchar(15) NOT NULL REFERENCES TEACHER(T_ID), 
--     CONSTRAINT PK_BELONGS_TO PRIMARY KEY (DeptNo, TeacherID)
-- );

-- CREATE TABLE OPTS_FOR (
--     StudentID varchar(15) NOT NULL REFERENCES STUDENT(S_ID), 
--     CourseID varchar(15) NOT NULL REFERENCES COURSE(C_ID), 
--     CONSTRAINT PK_OPTS_FOR PRIMARY KEY (StudentID, CourseID)
-- );

-- CREATE TABLE OFFERS (
--     DeptNo int NOT NULL REFERENCES DEPARTMENT(D_NO), 
--     CourseID varchar(15) NOT NULL REFERENCES COURSE(C_ID), 
--     CONSTRAINT PK_OFFERS PRIMARY KEY (DeptNo, CourseID)
-- );


-- INSERTING VALUES INTO THE TABLES

-- TRUNCATE TABLE DEPARTMENT; 

-- INSERT INTO DEPARTMENT VALUES   --D_NO, D_NAME, LOC
-- ( 1204, 'Dept of CS', 'TW-29 Block'),
-- ( 1390, 'Dept of ECE', 'SFS-14,15 Block');

-- INSERT INTO DEPARTMENT(D_NO, D_NAME) VALUES
-- ( 2207, 'Dept of Design');

-- SELECT * FROM DEPARTMENT;

-- INSERT INTO TEACHER VALUES -- NAME, PHONENO, EMAILID, T_ID 
-- ('Mrs. Sonam', '99998888', 'sonam@gmail.com', 'AGH1908'),
-- ('Ms. Monia', '99997777', 'monia@gmail.com', 'SKO7897');

-- INSERT INTO TEACHER(NAME, EMAILID, T_ID) VALUES 
-- ('Mr. Sanjay', 'sanjay@gmail.com', 'KGY1702');

-- SELECT * FROM TEACHER;

-- INSERT INTO STUDENT VALUES
-- ('Sandali Singh', '9315248049', 'sandalisingh_se20b9_16@dtu.ac.in', '2K20/SE/117', 117, 'SE A2 2020-24'),
-- ('Selena Gomez', '8888811111', 'selenagomez_ece21b8_84@dtu.ac.in', '2K20/ECE/84', 173, 'ECE B8 2021-25');

-- INSERT INTO STUDENT(NAME, EMAILID, S_ID, ROLLNO, BATCH) VALUES
-- ('Amitabh Bachchan', 'amitabhbachchan_ce21k8_73@dtu.ac.in', '2K20/CE/73', 73, 'CE K8 2021-25');

-- SELECT * FROM STUDENT;

-- INSERT INTO COURSE VALUES
-- ('SE-208', 'Software Engg.', 4, 40),
-- ('FEC-58', 'EVS', 2, 20);

-- INSERT INTO COURSE(C_ID, C_NAME) VALUES
-- ('ECE-23', 'Comp System & Arch');

-- SELECT * FROM COURSE;

-- INSERT INTO HEADED_BY VALUES
-- ( 1204, 'AGH1908'),
-- ( 1390, 'KGY1702');

-- SELECT * FROM HEADED_BY;

-- INSERT INTO BELONGS_TO VALUES
-- ( 1204, 'AGH1908'),
-- ( 1390, 'KGY1702'),
-- ( 1390, 'SKO7897');

-- SELECT * FROM BELONGS_TO;

-- INSERT INTO OPTS_FOR VALUES
-- ( '2K20/SE/117', 'ECE-23'),
-- ( '2K20/CE/73', 'SE-208'),
-- ( '2K20/CE/73', 'FEC-58'),
-- ( '2K20/SE/117', 'FEC-58');

-- SELECT * FROM OPTS_FOR;

-- TRUNCATE TABLE OFFERS; 

-- INSERT INTO OFFERS VALUES
-- ( 1390, 'ECE-23'),
-- ( 1204, 'SE-208');

-- SELECT * FROM OPTS_FOR;



-- SELECT * FROM DEPARTMENT;
-- SELECT * FROM TEACHER;
-- SELECT * FROM STUDENT;
-- SELECT * FROM COURSE;
-- SELECT * FROM HEADED_BY;
-- SELECT * FROM BELONGS_TO;
-- SELECT * FROM OPTS_FOR;
-- SELECT * FROM OFFERS;


-- SELECT STUDENT.NAME, OPTS_FOR.StudentID, COURSE.C_ID, COURSE.C_NAME FROM STUDENT, OPTS_FOR, COURSE
-- WHERE STUDENT.S_ID=OPTS_FOR.StudentID AND OPTS_FOR.CourseID=COURSE.C_ID AND STUDENT.NAME='Sandali Singh';


-- UPDATE STUDENT
-- SET PHONENO='9876543210'
-- WHERE NAME='Amitabh Bachchan';
 
-- SELECT * FROM STUDENT;

-- DELETE FROM HEADED_BY WHERE HeadOfDept='AGH1908';
-- SELECT * FROM HEADED_BY;


-- ALTER TABLE HEADED_BY
-- ADD NEW_COLUMN varchar(20);

-- SELECT * FROM HEADED_BY;

-- TRUNCATE TABLE HEADED_BY;
-- SELECT * FROM HEADED_BY;

DROP DATABASE UNIVERSITY;






